name: casetamartiicarmeta-prod

services:
  casetamartiicarmeta-prod:
    container_name: casetamartiicarmeta-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy

      - traefik.http.routers.casetamartiicarmeta-prod.rule=Host(`casetamartiicarmeta.com`)
      - traefik.http.routers.casetamartiicarmeta-prod.entrypoints=websecure
      - traefik.http.routers.casetamartiicarmeta-prod.tls=true
      - traefik.http.routers.casetamartiicarmeta-prod.tls.certresolver=letsencrypt
      - traefik.http.services.casetamartiicarmeta-prod.loadbalancer.server.port=3000

      - traefik.http.routers.casetamartiicarmeta-prod-http.rule=Host(`casetamartiicarmeta.com`)
      - traefik.http.routers.casetamartiicarmeta-prod-http.entrypoints=web
      - traefik.http.routers.casetamartiicarmeta-prod-http.middlewares=casetamartiicarmeta-prod-redirect
      - traefik.http.middlewares.casetamartiicarmeta-prod-redirect.redirectscheme.scheme=https

networks:
  traefik-proxy:
    external: true
