name: casetamartiicarmeta-dev

services:
  casetamartiicarmeta-dev:
    container_name: casetamartiicarmeta-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.development
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy

      - traefik.http.routers.casetamartiicarmeta-dev.rule=Host(`test.casetamartiicarmeta.com`)
      - traefik.http.routers.casetamartiicarmeta-dev.entrypoints=websecure
      - traefik.http.routers.casetamartiicarmeta-dev.tls=true
      - traefik.http.routers.casetamartiicarmeta-dev.tls.certresolver=letsencrypt
      - traefik.http.services.casetamartiicarmeta-dev.loadbalancer.server.port=3000

      - traefik.http.routers.casetamartiicarmeta-dev-http.rule=Host(`test.casetamartiicarmeta.com`)
      - traefik.http.routers.casetamartiicarmeta-dev-http.entrypoints=web
      - traefik.http.routers.casetamartiicarmeta-dev-http.middlewares=casetamartiicarmeta-dev-redirect
      - traefik.http.middlewares.casetamartiicarmeta-dev-redirect.redirectscheme.scheme=https

networks:
  traefik-proxy:
    external: true
