name: Deploy test

on:
  push:
    branches:
      - integration/public-site

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy test branch locally
        run: |
          cd ~/apps/casetamartiicarmeta-test
          git fetch origin
          git checkout integration/public-site
          git pull origin integration/public-site
          docker compose -f docker-compose.test.yml up -d --build
